### ISSUE TITLE
API fails for toront aug 4

### ISSUE THREAD

**Issue by ghost** [buelowp/sunset#1]
Hi, What I am doing wrong?

http://173.249.22.226/share458900/timezone.png

**Comment by buelowp** [comment]
I'm sorry, I don't seem to be able to open that link. What issue are you having?

EDIT: It worked for me the second time.

I suspect you are not setting your location correctly using a double for latitude and longitude. The library will not work if you do not accurately set the date and the location. Higher precision numbers for latitude and longitude work better. Note that it does not track time either, so you must set the date and timezone as often as needed for your application.

**Comment by ghost** [comment]
Hi,
Thank you ill try it after the long weekend. Appreciate. I'll let you know how it works.
EDIT: Still, I don't get valid or appropriate values. Is something I miss.
Code:

    double lat = 43.653908; // from  https://www.latlong.net/place/toronto-city-hall-toronto-on-canada-11756.html
    double lon = -79.384293;
    char buf[16];
    time_t t = time(NULL);
    struct tm tm = *localtime(&t);
    ::strftime(buf, sizeof(buf), "%z", &tm);
    int tz = ::atoi(buf)/100; // timezone -4
    printf("-Inputs\n LAT LONG: %lf %lf \n",lat,lon);
    std::cout << " DATE: " << tm.tm_year+1900<<":"<<tm.tm_mon<<":"<<tm.tm_mday << " tzone: " << tz<<"\n";
    SunSet st(lat, lon, tz);
    st.setCurrentDate(tm.tm_year+1900,tm.tm_mon,tm.tm_mday);

    int sr = st.calcSunrise();
    int sd = st.calcSunset();
    std::cout << "Output:\n Sun rise: " << sr <<"min = "<< sr/60 <<":"<< abs(sr%60)<<"\n";
    std::cout << " Sun set: "  << sd <<"min = "<< sd/60 <<":"<< abs(sr%60)<<"\n";

Console:

    -Inputs
     LAT LONG: 43.653908 -79.384293 
     DATE: 2018:7:6 tzone: -4
    Output:
     Sun rise: -292min = -4:52
     Sun set: 626min = 10:52   
     // which differ from: https://www.timeanddate.com/sun/canada/toronto
     // also tried with tm.mon +1 = 8

**Comment by buelowp** [comment]
Sorry, I didn't see this. Don't use negative longitude. Longitude  doesn't make a difference positive or negative. That should fix the problem.

**Comment by ghost** [comment]
Thank you. Already figured that. :).
