### ISSUE TITLE
Incorrect Sample Longitude in readme.md

### ISSUE THREAD

**Issue by ThothK** [buelowp/sunset#10]
Hi,

The example longitude to readme.md is:
"#define LONGITUDE	89.0000"
I believe this is incorrect as it would be for a location in China. If the longitude is correct, then it conflicts with the time zone of -5.
I believe the longitude value should be:
"#define LONGITUDE	-89.0000"

**Comment by buelowp** [comment]
The original code could not use negative numbers. This is called out in the README as well. With the 1.0.7 release, it does account for negative longitude by converting it. However, to match the original code, I do not change this requirement.
