### ISSUE TITLE
Civil, nautical and astronomical twilight?

### ISSUE THREAD

**Issue by Glichy** [buelowp/sunset#15]
Would it be possible to add them to this library?
My use case needs to know the time difference between sunset and them and i can't seem to find a library that has them.
I think it mainly needs functions similar to calcHourAngleSunrise and calcHourAngleSunset that use 96, 102 and 108 instead of 90.833 but i'm not completely sure about that.
Thank you.

**Comment by buelowp** [comment]
I think that would be very neat, but I do not have the math/astronomy background to do so. I didn't invent this, I just packaged it up so people could more easily use it. I may be able to add it if you gave me the math maybe? Otherwise, probably not.

**Comment by Glichy** [comment]
I've looked around for a while and it seems to just be what i mentioned:

https://github.com/mikereedell/sunrisesunsetlib-java/blob/master/src/main/java/com/luckycatlabs/sunrisesunset/Zenith.java#L24

https://github.com/mourner/suncalc/blob/master/suncalc.js#L102

https://github.com/caarmen/SunriseSunset/blob/e8e73f563b90a50d032d4fa0221e4726ca8516f9/library/src/main/java/ca/rmen/sunrisesunset/SunriseSunset.java#L47

https://math.stackexchange.com/questions/947718/how-to-calculate-civil-twilight-timings

Having the option to use a custom angle might also be useful to others.

**Comment by buelowp** [comment]
I think I can do this. The original code did apply the sunrise/sunset angles directly as hardcoded values. I'll work on it this week and next and see what I can come up with. Can't promise this will work, but I think I see a path.

**Comment by buelowp** [comment]
I had some time this morning, and it wasn't as hard as I thought it might be. I've added new API's to match the new calculations. I've tested them locally to be accurate. Let me know if this new branch works for you. I'll merge it soon after some more testing.
