### ISSUE TITLE
Support for fractional time zones

### ISSUE THREAD

**Issue by Glichy** [buelowp/sunset#17]
There are several places where the time zone doesn't differ by a whole number:
https://www.timeanddate.com/time/time-zones-interesting.html

I think it mainly just needs `tzOffset` to be either a float or a double and overload the functions `setPosition` and `setTZOffset` (and `SunSet`?).

**Comment by buelowp** [comment]
Interesting. Yeah, that's going to be complicated. It will require some breakage of the API, and a lot of people use this. Let me test it and see what happens first to make sure I don't screw anyone else over. It's a valid point.

Just overloading isn't the question, you need to know which overload is enabled (int or double) to make it work. I think there is a solution, but need to play with it.

**Comment by buelowp** [comment]
Fixed using branch alternativecalculations and will be merged shortly. It turned out to be trivial to implement, though testing has only been done on X86 Linux. More testing on an M4 to happen later this week.
