### ISSUE TITLE
Warn Windows users about filename collision

### ISSUE THREAD

**Issue by Glichy** [buelowp/sunset#19]
Windows filenames are case insensitive, so `sunset.h `and `SunSet.h` can't be present in the same folder.

When downloading and extracting the repo zip, it will ask to replace or rename one of them. (In my case, 7zip will extract `SunSet.h` first then ask to replace it with `sunset.h` or auto rename.)

GitHub Desktop seems to always end up with `SunSet.h` but with the contents of `sunset.h` when trying to clone the repo.

PlatformIO seems to end up with `sunset.h` but with the contents of `SunSet.h`. Including it in projects is also case insensitive. (Tried with `SUnSeT.H` and it compiled just fine for both the ESP8266 and the STM32F103.)

**Comment by buelowp** [comment]
The readme indicates I don't do windows. The challenge is that SunSet.h was the original name, and the Particle build system forced me to add a new header called sunset.h to match the package name. I think the only way to fix this is to just break the thing and migrate to just sunset.h and sunset.cpp completely.

**Comment by buelowp** [comment]
I thought about it and squashed the filenames to be lower case only. Check it out, but there should no longer be collisions or issues on case insensitive filesystems.

**Comment by Glichy** [comment]
Yeah, that did it.
By the way, thank you for all the work you've been doing on this library.
