### ISSUE TITLE
Negative longitude

### ISSUE THREAD

**Issue by francescozanellaDL** [buelowp/sunset#2]
Hi,
thank you very much for this library.
If I can't use negative longitude, what do I have to use instead of -80 (for example)? +80? 360-80=280? other?
Thanks

**Comment by buelowp** [comment]
Because the only change is latitude in terms of when the sun rises and falls, your longitude can be positive no matter what without changing the result. 80 or -80 are the same in terms of where the sun comes up via latitude. You don't need to do the math, just use 0 to 180.
