### ISSUE TITLE
Request for documentation -- help with specific use case

### ISSUE THREAD

**Issue by kebekus** [buelowp/sunset#27]
Dear Buelowp,

I was wondering if I use your library correctly. If you have a minute, could you please tell me how to use your library correctly for the following use case? Through trial and error, I have found a way to compute the following data, but I am unsure if my solution is actually correct.

I have the following data:

- Current Time and Date in UTC
- Coordinate of a geographic location on earth (might be north of the arctic circle)

I would like to compute the Time and Date (in UTC) of the next sunset or sunrise at the location, whatever comes earlier.

Best,

Stefan Kebekus.

**Comment by buelowp** [comment]
Be careful with UTC, as it gets confusing easily. However, that far north it may not matter. I believe you are using it correctly, simply set the TZ offset to 0, and call calcSunrise and calcSunset. Time is meaningless to the library, only date, so as long as your date is correct, the results should be correct as well. If your timezone offset is 0, it's the same as calling calcSunriseUTC().

Let me know if that helps.

**Comment by buelowp** [comment]
Let me know if that helps. Or did I not understand the problem?

**Comment by kebekus** [comment]
You reply has helped, thank you! I will therefore close the issue now.
