### ISSUE TITLE
Add option to override cmake build settings via variables

### ISSUE THREAD

**Issue by enbyted** [buelowp/sunset#28]
Hi, thanks for making this library!

I want to integrate this library into embedded project as a git submodule. Unfortunately it's not possible because of this code in your CMakeLists.txt:
```cmake
set (CMAKE_CXX_STANDARD 14)
set (CMAKE_CXX_FLAGS -pthread)
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-long-long -pedantic")
```

`-pthread` appears to be not needed at all (probably it's required for gtest), also depending on target platform it might not be correct way to link pthread. For example see [this stackoverflow question](https://stackoverflow.com/questions/1620918/cmake-and-libpthread).
Also because you use `set (CMAKE_CXX_FLAGS -pthread)` instead of `set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread)"` it resets all previously set flags.

`set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-long-long -pedantic")` in my opinion should also be optional - gated behind a flag. Maybe you should also consider using [target_compile_options](https://cmake.org/cmake/help/latest/command/target_compile_options.html)

`add_library (${PROJECT_NAME} SHARED ${SOURCES})` - embedded platforms usually don't support shared libraries, while cmake ignores this and issues a warning this really should be configurable with a variable.

**Comment by buelowp** [comment]
HA, no, you're right. That's a hold over from a long time ago. I didn't fix it, and no one complained. I will work on a fix today/tomorrow and post a release when I get a chance. I'll let you know when it's on master to see if the fix works for you.

***EDIT***
Can you tell me which version of cmake you are using?

**Comment by enbyted** [comment]
Oh, thanks for quick response.

I'm using latest cmake, build daily from master. On other machines I'm on 1.12-1.16 though.

**Comment by buelowp** [comment]
Are you sure about the cmake version? Latest is 3.18.4, and the CMakeLists.txt doesn't support less than 3.0.

I've got a 3.x compatible solution, but it's cleaner starting with 3.1. It's not critical though, so I'm going to check my version in shortly.

**Comment by buelowp** [comment]
Ok, give this a shot? I've moved the pthread code to gtest which I think cleans this up the right way.

**Comment by buelowp** [comment]
One other thing. A bug was found, and fixed on master a few days ago. #26 highlighted an issue with not returning the float remainder but the full value instead. Testing seems to show this doesn't have an impact either way, but I made the change to match the original code anyway. Please take a few minutes to make sure your results are correct. Testing on my side on a few platforms shows it works in all cases I can find, but I can't imagine that if the fmod was critical, that it should have ever worked. That I don't get a change in results is odd, so I'm a little concerned.

**Comment by enbyted** [comment]
> Are you sure about the cmake version? Latest is 3.18.4, and the CMakeLists.txt doesn't support less than 3.0.

Sorry, I meant 3.x versions of course.

> Ok, give this a shot? I've moved the pthread code to gtest which I think cleans this up the right way.

This works, mostly.

I added manually `target_include_directories(${PROJECT_NAME} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src")` instead of `include_directories(BEFORE "${CMAKE_CURRENT_SOURCE_DIR}/src")`.
This causes CMake to automatically add apropriate include directoreis when I use `target_link_libraries(target PRIVATE sunset)`. Without that I would have to manually add include directories in my app's CMakeLists

> One other thing. A bug was found, [...]

I'm using latest master and I'm getting accurate results on Cortex-M7 with double precision FPU (STM32H7).
BTW. This doesn't change the result probably because it's only used as input to trigonometric functions (and they're periodic). in `calcSunTrueLong` you're adding `calcGeomMeanLongSun` and `calcSunEqOfCenter`, but the first one I think will always be big and the second one always be small. Thus the change in result should be minimal. 
I spent only 5 minutes looking at that, I might have overlooked something - this really is quite complex math.

**Comment by enbyted** [comment]
Oh, and I missed one thing.

`set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-long-long -pedantic")` causes my build to fail with a rather weird error: `{my target name} uses VFP register arguments, ../external/sunset/libsunset.a(sunset.cpp.obj) does not`. This is inherently caused by some of my compiler flags not being passed when building your library.

Actually even `set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")` triggers that error.

When I change it to use more modern `target_compile_options(${PROJECT_NAME} PRIVATE -Wall -Wno-long-long -pedantic)` there is no error. That's probably because of some variable scope issue, I would have to investigate further to see if that is a fault on my side. Though I'm 99.9% sure that you could switch to this newer syntax without breaking anything - it plays nicer with different build configurations.

**Comment by buelowp** [comment]
I like the target_compile_options change, so I'll pull that one in.

I can't make the target_include_directories work for standard builds. I don't think that's the correct way to do what you want to do, but I can't figure out how to make it work for both cases. Since it does for other projects, I suspect it's just something I don't know how to do exactly. For now, I can't switch, the normal cmake .. use case doesn't work. I'll keep looking at it. You can see the other change on master now.

**Comment by buelowp** [comment]
Ok, figured out my issue with target_include_directories and pushed a change with that. See if the latest master works for you.

**Comment by enbyted** [comment]
> I like the target_compile_options change, so I'll pull that one in.

Thanks for that.

> I can't make the target_include_directories work for standard builds.

How it doesn't work? It is meant to replace `include_directories`.
I just tested it with:
```cmake
add_library (${PROJECT_NAME} SHARED ${SOURCES})
set_target_properties(${PROJECT_NAME} PROPERTIES VERSION ${PROJ_VERSION} SOVERSION ${PROJ_VERSION_MAJOR} )
target_compile_options(${PROJECT_NAME} PRIVATE -Wall -Wno-long-long -pedantic)
target_include_directories(${PROJECT_NAME} PUBLIC BEFORE "${CMAKE_CURRENT_SOURCE_DIR}/src")
```

And got:
```
enbyted@enbyted-ubuntu:~/praca/enea/sunset/build$ cmake .. -DCMAKE_INSTALL_PREFIX=../install
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/enbyted/praca/enea/sunset/build
enbyted@enbyted-ubuntu:~/praca/enea/sunset/build$ make install
Scanning dependencies of target sunset
[ 50%] Building CXX object CMakeFiles/sunset.dir/src/sunset.cpp.o
[100%] Linking CXX shared library libsunset.so
[100%] Built target sunset
Install the project...
-- Install configuration: ""
-- Installing: /home/enbyted/praca/enea/sunset/install/lib/libsunset.so.1.1.4
-- Installing: /home/enbyted/praca/enea/sunset/install/lib/libsunset.so.1
-- Installing: /home/enbyted/praca/enea/sunset/install/lib/libsunset.so
-- Installing: /home/enbyted/praca/enea/sunset/install/include/sunset.h
```

Maybe I don't understand something about your standard usecase?


EDIT:

> Ok, figured out my issue with target_include_directories and pushed a change with that. See if the latest master works for you.

Oh, okay, I'll test in a moment.

**Comment by buelowp** [comment]
Yeah, I got an error, but it was because I didn't move the directive to after the add_library, so it failed. Took me a bit to see that.

**Comment by enbyted** [comment]
Actually we were both working on this, but you beat me to the final pushes.

You might want to take a look at: https://github.com/enbyted/sunset/commit/e146fb79962c4194d4ed82f99d93ccd281061c85
This fixes the warning on platforms that don't support shared libraries.

Also, you might consider this: https://github.com/enbyted/sunset/commit/f6a8be9e2730481a29131d034c3625212a71d92e
Though I'm not 100% sure it changes anything in 99.99% of usecases besides requiring higher CMake version (though 3.1 is still quite old).

**Comment by enbyted** [comment]
And your changes fix the errors for me, so this issue can be closed.

If you want these commits I can rebase my branch on top of current master, though the raw patch should apply just fine.

**Comment by buelowp** [comment]
Yeah, 3.0.2 is old, but I have worked with some consumers who use older build systems where moving the minimum required may cause problems. Since I'm not doing anything that requires newer, it doesn't make a lot of sense to switch for now.

I'll pull the shared library change, but I'm going to default to building shared like you have it. I like that change too. I'll push it in a bit.

**Comment by enbyted** [comment]
Awesome, thanks for very quick cooperation on this. I wish my commercial partners where this fast!

BTW. I rebased the repo, so you can just merge if you want.

**Comment by buelowp** [comment]
I just pushed it in a new ticket #29 so I can track it. Just a copy of yours though, so you should be good to go.
