### ISSUE TITLE
Declaration Syntax error in header file

### ISSUE THREAD

**Issue by amanpreetk93** [buelowp/sunset#3]
![capture](https://user-images.githubusercontent.com/39523346/47552606-b8f54f80-d922-11e8-91bf-6a34c4af2350.PNG)
Unable to include it in the main cpp file.

**Comment by buelowp** [comment]
To be honest, I have no idea. Are you building with a C++ capable compiler? I have no experience with DosBox, so I can't say how that might work. Given that it chokes on the class keyword, I would guess you aren't using a c++ compiler.
