### ISSUE TITLE
Member functions that should be const aren't

### ISSUE THREAD

**Issue by enbyted** [buelowp/sunset#31]
Almost all functions of this library are purely computational thus, can be marked const.

I think only these functions need to be non-const:
```c++
    void setPosition(double, double, int);
    void setPosition(double, double, double);
    void setTZOffset(int);
    void setTZOffset(double);
    double setCurrentDate(int, int, int);
```

This allows to preserve const correctness of client code.

This is related to [Con.2 from CppCoreGuidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-fct).
Also you might consider adding `noexcept` [F.6 from CppCoreGuidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-noexcept)

**Comment by buelowp** [comment]
Ahh, good idea. Hadn't thought of this, but yeah, I'll make some updates and see what happens.

**Comment by buelowp** [comment]
Since I'm bored, and just started a new job on Monday, I just did this while I was thinking about it. Testing works, though I haven't tried it on my Photon yet. I don't expect that would be a problem though. See master and let me know if you think I missed anything or made a mistake.

**Comment by enbyted** [comment]
This works for me and I don't see a reason why this should break anything.

You missed two depreciated ones, I commented in the commit to point out the exact place.

**Comment by buelowp** [comment]
I did that on purpose, the deprecated are as is, and won't be changed to avoid confusion. Don't want anyone to think I'm going to go on supporting them by making changes.
