### ISSUE TITLE
Expose `calcAbsSunset` style interface, so custom offsets can be used

### ISSUE THREAD

**Issue by enbyted** [buelowp/sunset#32]
I need to adjust the offset for sunrise/sunset calculation to match the one used in existing hardware.
`calcAbsSunset` can't be exposed directly, as it doesn't take into account timezone offset.

I'm proposing to add `calcCustomSunset` and `calcCustomSunrise` that would take offset as an argument and calculate appropriate time accounting for timezone offset. then all existing functions could be modified to only call the new interface with appropriate constant.

**Comment by buelowp** [comment]
Interesting, I've added two new functions, let me know if that's what you were looking for.

**Comment by buelowp** [comment]
I also pushed a change to the doxygen documentation just now.

**Comment by enbyted** [comment]
Thanks for that, that's exactly what I needed. It's basically the same that I did for myself plus the documentation and examples.

With that change maybe it would be good to replace all of `return calcAbsSunset(SUNSET_OFFICIAL) + (60 * m_tzOffset);` with `return calcCustomSunrise(SUNSET_OFFICIAL);`, so that the timezone calculation code is kept in one place?
That's merely a code style thing, though.

**Comment by buelowp** [comment]
Just pushed that, take a look and if you're good, I'll close this.

**Comment by enbyted** [comment]
Looks good to me, closing.
