### ISSUE TITLE
Remove unnecessary define statements

### ISSUE THREAD

**Issue by enbyted** [buelowp/sunset#33]
Since C++14 is required for this project these define statements
```c++
#define SUNSET_OFFICIAL         90.833
#define SUNSET_NAUTICAL         102
#define SUNSET_CIVIL            96
#define SUNSET_ASTONOMICAL      108

#define SUNSET_INVALID_TZ_D     99.9
#define SUNSET_INVALID_TZ_I     99
```

can easily be converted to `static constexpr double` inside the class body - removing the need for defines. 
Also please consider adding documentation to them, as first 4 are quite clear to me, but I'm clueless what's the usage of the latter 2.

**Comment by buelowp** [comment]
Good point. I migrated the four defines to be constexpr, and dropped the invalid. They aren't used, but were part of a branch I was working on for some validation a while back. I didn't notice they snuck into master.

Updated the four with documentation, and dropped two. You'll see the commit shortly.
