### ISSUE TITLE
Remove dependency on ctime

### ISSUE THREAD

**Issue by enbyted** [buelowp/sunset#38]
There is only one function that uses ctime header - `int moonPhase() const`. In some applications (including mine) this header is unavailable or local time is not available (so the `std::time` is unavailable).

Since it's really only convenience wrapper it would be nice if it was possible to disable it with compile option.

**Comment by buelowp** [comment]
What platform are you using that doesn't have ctime? The problem here is that I would have to jump through some non C++ hoops to get current time for that convenience function. I use it for my projects directly, and I know at least a few others do as well.

I would rather not remove a function unless the platform is one I support directly. At this time, I'm not aware of a platform that doesn't have ctime that I can test against.

**Comment by enbyted** [comment]
STM32H7 (with gcc toolchain with much of the libstdc++ removed), using std::time causes dependency on _gettimeofday from clib (which I would have to provide). For me it would be enough if this function and include was wrapped with, for example: `#ifndef SUNSET_EXCLUDE_CTIME` or something like that. 

Currently I'm just commenting out this code as I can't really remove this deependency at link time since I'm using stack unwinding symbols which make it really hard for linker to remove not really used functions (since they're referenced by the unwinding tables).

**Comment by buelowp** [comment]
That's the micro, what's the SW platform or RTOS? I don't think at this time I'm going to do the ifdef as that would set a precedent that might result in a LOT of ifdefs for things people don't want or like. Unless this SW platform is one that I explicitly support and can test against, I am not going to remove anything.

One way you could do this, and support others that may be interested in using the exact same platform as you, would be to fork the repo,  remove the function and include line, and update the readme to focus specifically on your target (remove what I advertise in mine). Then, if someone else has the same issue, they are free to ask me, and I can point them at your repo, or they may find it on their own. This would be my preference over code changes that reduce functionality I use, or precedents like "The feature works, but I don't like it, can you remove/change it for me?".

**Comment by enbyted** [comment]
> That's the micro, what's the SW platform or RTOS?

Custom setup with FreeRTOS. That's mostly a toy project for me to experiment with different setups for building embedded firmware.

> One way you could do this, and support others that may be interested in using the exact same platform as you, would be to fork the repo, remove the function and include line, and update the readme to focus specifically on your target (remove what I advertise in mine). Then, if someone else has the same issue, they are free to ask me, and I can point them at your repo, or they may find it on their own. This would be my preference over code changes that reduce functionality I use, or precedents like "The feature works, but I don't like it, can you remove/change it for me?".

This seems fine until a few years from now you update the library, I've already forgot about it and now people have issues with my, ancient, fork and go to you for support. 

> I don't think at this time I'm going to do the ifdef as that would set a precedent that might result in a LOT of ifdefs for things people don't want or like. Unless this SW platform is one that I explicitly support and can test against, I am not going to remove anything.

I hear you and won't pressure this issue as it's a really small thing, that most probably won't affect many people. In 99.9% of cases unused function will be stripped by linker before it figures out that `_gettimeofday` is missing. It's just my weird setup that I'm actually using these unwinding tables which causes all sorts of problems... I'll stick with commenting out that one function as that's the easiest solution for me. Never hurts to ask though!

Have a wonderful day (I believe it's day in the US)!

**Comment by buelowp** [comment]
Ok, that's fine. Thank you for the feedback and for closing.
