### ISSUE TITLE
Lack of documentation on: how to trigger something on sunset and sunrise, clock mode (12 or 24 hour clock)

### ISSUE THREAD

**Issue by Iftikhar-Omar** [buelowp/sunset#39]
Please do include a simple example on how to turn a pin HIGH on sunset and how to turn it LOW on sunrise. It'll make this library easier to work on and use on various projects. Please clearly state if it returns time in 24 hour format or 12 hour format.

**Comment by buelowp** [comment]
I'll add some notes on how to calculate the minutes past midnight, then it's just a if (mpm > sunset) digitalWrite(PIN, HIGH);
Give me a little bit to add that.

**Comment by buelowp** [comment]
Updated the ESP example so it will now toggle the builtin LED after sunset.

https://github.com/buelowp/sunset/commit/b9b06fc0e77be74422da43d7bf5eae8766009209
