### ISSUE TITLE
Wrong Results for Rome

### ISSUE THREAD

**Issue by piarullir** [buelowp/sunset#4]
I have wrong UTC values (and conseguently localtimes) for Italy - Rome with this sample code:

// Rome Coord
#define CUR_LAT 41.89193
#define CUR_LON 12.51133

#define TIMEZONE_DEC 1
#define TIMEZONE_JUN 2

int getHoursFromVal(int minutes) {
return (int) (minutes / 60);
}

int getMinutesFromVal(int minutes) {
return minutes - (getHoursFromVal(minutes) * 60);
}

void printCalculation(double lat, double lon, int tz, int year, int month, int day) {
SunSet s;
s.setCurrentDate(year, month, day);
s.setPosition(lat, lon, tz);
double sunriseUTC = s.calcSunriseUTC();
double sunsetUTC = s.calcSunsetUTC();
std::cout << "###################### "<< std::endl;
std::cout << "Latitude:" << lat << " | Longitude:" << lon << " | Year:" << year << " | Month:" << month << " | Day:" << day << " | Tz:" << tz << std::endl ;
std::cout << "Sunrise UTC Val: " << sunriseUTC << " (" << getHoursFromVal(sunriseUTC) << ":" << getMinutesFromVal(sunriseUTC) << " past midnight)" << std::endl;
std::cout << "Sunset UTC Val: " << sunsetUTC << " (" << getHoursFromVal(sunsetUTC) << ":" << getMinutesFromVal(sunsetUTC) << " past midnight)" << std::endl;
std::cout << std::endl;
}

int main() {
double lat = CUR_LAT;
double lon = CUR_LON;
int year = 2018;
int month = 6;
int day = 1;
int tz = TIMEZONE_JUN;
printCalculation(lat, lon, tz, year, month, day);
month = 12;
tz = TIMEZONE_DEC;
printCalculation(lat, lon, tz, year, month, day);
}

##################################
Console output
##################################

######################
Latitude:41 | Longitude:12 | Year:2018 | Month:6 | Day:1 | Tz:2
Sunrise UTC Val: 318.25 (5:18 past midnight) // Wrong! -> Attended: 3:18 -> utc+2=5:18
Sunset UTC Val: 1213.81 (20:13 past midnight) // Wrong! -> Attended: 18:13 -> utc+2=20:13

######################
Latitude:41 | Longitude:12 | Year:2018 | Month:12 | Day:1 | Tz:1
Sunrise UTC Val: 473.311 (7:53 past midnight) // Wrong! -> Attended utc 5:53 -> utc+1=6:53
Sunset UTC Val: 1040.49 (17:20 past midnight) // Wrong! -> Attended utc 15:20 -> utc+1= 16:20

It seems that UTC have a 2 hours offset, what i'm doing wrong?

**Comment by buelowp** [comment]
I think this is just a little bit of confusion. It's not the UTC value for sunrise and sunset. It's the UTC time when Sunrise happens at your latitude and longitude. If you were to set lat and lon to 0 and 0 and run it again, you would get the correct UTC sunrse and sunset. Otherwise, I'm getting the right values for your location in my testing.

**Comment by piarullir** [comment]
There is no confusion, after last commit f6e3c1674376f53e3b0432560b2f55e5993d821c all is working as expected (for my example).

Thank you and good work!
