### ISSUE TITLE
Publish latest version to Platformio package library

### ISSUE THREAD

**Issue by j4m3s** [buelowp/sunset#42]
Hi

Would you be able to publish v1.1.6 to the platformio package library please?  v1.1.3 is the latest in there so is a couple of versions behind:
```
buelowp/sunset
Library • 1.1.3 • Published on Thu May 28 10:41:38 2020
Allows calculation of sunrise, sunset, and moonphase. Calculates Sunrise and Sunset, along with the Civil, Nautical, and Astronomical times for Sunrise/Sunset. It can also tell you the moon phase for a given time.
```

Thank you!

**Comment by buelowp** [comment]
Interesting, github didn't notify me. Yes, I'll work on that this weekend. I think I'm going to spin 1.1.7 anyway, so that would be a good time to do so.

**Comment by buelowp** [comment]
I need to dig into this. I never put together a library.json file, and have never used PIO much. The timing seemingly indicates I did upload that, but I would have kept the json file I used. Anyway, I'll have to figure it out. I'm not familiar with PIO. And if I didn't originally publish it, I may not be able to take it over.

I just pushed a library.json, and will look into supporting this going forward, but the issue I have is that I don't support many architectures that PIO does, and I will need to test the allowed platforms keyword before I make it public.

**Comment by buelowp** [comment]
Ok, I'm having some issues with my account. I'll tackle this if they help me fix it.

**Comment by buelowp** [comment]
I just got a message that they fixed my account. I'll do the upload in a bit.

Uploaded, pending review.

**Comment by j4m3s** [comment]
If you need help testing, I use Linux native and esp32. The library works brilliantly on both as a git submodule so I'll be shocked if it doesn't work as a lib_dep but will happily check, especially given the new library.json file.

**Comment by buelowp** [comment]
I would appreciate testing for ESP. I don't use them much anymore, so I don't have anything setup to do the testing. The Linux side is used in several boxes around my house every day.

**Comment by j4m3s** [comment]
Sorry for the delay Peter.  All looks good on the ESP32, and v1.1.7 pulls through from the Platformio package library beautifully now.  Thank you!
