### ISSUE TITLE
check for NaN in calcHourAngleSunset/-Sunrise

### ISSUE THREAD

**Issue by stepkun** [buelowp/sunset#43]
Hello, 
great work your library. 
On my location around 21st of June the lib gives no proper values for astronomical sunrise/sunset. Reason is that the hour Angle goes near Pi, so that the result of acos(...) results in  NaN.
Adding 
`
if(std::isnan(HA)) 
        HA =  M_PI;
`
in both functions Solved the problem for me.

Kind regards
Stephan

**Comment by buelowp** [comment]
Would you be willing to provide a patch and a test case for this? I'll merge and add you to the contributors. I'll confess, at first reading, I'm not sure how this fixes NaN, but I'd be happy to get more details.

***EDIT***
I mocked up my code with your suggestion, but I don't know how to use this. For my High Lat test, I get unreasonable numbers for sunrise and sunset by removing NaN. The point of NaN is to indicate that there *isn't* a sunrise/sunset at that time/date/location.

I'll be willing to investigate this more, but right now, unless I'm missing something, this change may cause more issues than the benefit for the fix.

**Comment by stepkun** [comment]
Weird thing. With your project environment I get completely different values.
I added a few tests in my fork  https://github.com/stepkun/sunset
This is the table I used to verify the expected values: https://www.timeanddate.de/sonne/deutschland/stuttgart
In my project environment I get proper values (I integrated only the sunset.cpp and sunset.h)

**Comment by buelowp** [comment]
I'm a bit confused, I grabbed your fork and built it, and none of the Stuttgart tests work for me, but that seems minor here (replaced _CT with _SG, tests still fail due to float resolution, not a problem). So, it seems you took out the NaN work though? And now it functions more correctly?

Why do you do the fp_rise work? That seems extraneous to me.

**Comment by stepkun** [comment]
Sorry for confusing you,
The commit was not properly done - it was 3 o'clock in the morning :-)
The fp_rise was something leftover from a set previous sessions, also using _CT instead of _SG.
I am dynamically calling the different calculations due to a surrounding routine which is same for all kinds of calls.
Doing the corrections it looks better now

[----------] Global test environment tear-down
[==========] 34 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 33 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SunsetTesting.MoonphaseNoArgs

 1 FAILED TEST

That Moonphase test fail, is that normal?

My original problem was a misunderstanding of your lib returning NaN together with a wrongly usage of  std::localtime(timestamp); Using it twice with different timestamps mixed the results, so I got the NaN where it should not have one.

Thanks for your help

**Comment by buelowp** [comment]
No, the error is not. I'm not sure what happened, but I'll have to fix that up. Moonphase should work, but it's clearly not right now.

OK, so the current behavior is correct then? I appreciate it and wish you luck. I have visited Stuttgart a few times, but not in the last 10 years unfortunately. I love that region of Germany and cannot wait to go back.

**Comment by stepkun** [comment]
Yes, the behaviour is correct, maybe you could mention that return of NaN in the Readme?

This region really is nice, especially if you live outside the Stuttgart city area but not too far away.

**Comment by buelowp** [comment]
Thanks, I updated the readme a bit. Let me know if you find that more clear.

**Comment by stepkun** [comment]
That clarifies it for me. Do you want to have a pull request to merge my Stuttgart tests?
