### ISSUE TITLE
Wrong times, problem with TZ and TzOffset

### ISSUE THREAD

**Issue by watzi3** [buelowp/sunset#48]
Hello, 

Somehow i cannot get the library to display correct values for my location in Austria. 
Austria is normally UTC+1 during winter and  UTC+2 (DST of 1h) between end of March and end of October. 
No matter what I enter as Timezone (1 or 2) the smallest difference to the actuall sunset time according to the internet is at least 1h and 4mins. 

My Date and Time that i feed the library are from an RTC and are correct and precise. 
Project runs on an ESP32 and programmed via VsCode (Platform IO). 

Here is my code: 
```
#include <RTClib.h>
#include <sunset.h>

#define TIMEZONE 2
#define LATITUDE 48.330
#define LONGITUDE 14.300

SunSet sun; 

void setup() {
  DateTime time = rtc.now(); 
  sun.setPosition(LONGITUDE,LATITUDE,TIMEZONE);
  sun.setCurrentDate(time.year(), time.month(), time.day()); 

  Serial.print("date: "); 
  Serial.print(time.day()); 
  Serial.print("."); 
  Serial.print(time.month()); 
  Serial.print("."); 
  Serial.println(time.year()); 
  Serial.print("Time: "); 
  Serial.print(time.hour()); 
  Serial.print(":"); 
  Serial.print(time.minute()); 
  Serial.print(":"); 
  Serial.println(time.second()); 
  Serial.println("__________________________________"); 

  int sunset = static_cast<int>(sun.calcSunset()); 
  Serial.print("Sunset: "); 
  Serial.println(sunset); 
  Serial.print("Sunset: "); 
  Serial.print(sunset/60); 
  Serial.print(":"); 
  Serial.println((sunset%60)); 
  Serial.println("__________________________________"); 

  sunset = static_cast<int>(sun.calcCivilSunset());
  Serial.print("Civil Sunset: "); 
  Serial.println(sunset); 
  Serial.print("Sunset: "); 
  Serial.print(sunset/60); 
  Serial.print(":"); 
  Serial.println((sunset%60));  
  Serial.println("__________________________________"); 

  sunset = static_cast<int>(sun.calcNauticalSunset());
  Serial.print("Nautical Sunset: "); 
  Serial.println(sunset); 
  Serial.print("Sunset: "); 
  Serial.print(sunset/60); 
  Serial.print(":"); 
  Serial.println((sunset%60));  
  Serial.println("__________________________________"); 

  sunset = static_cast<int>(sun.calcAstronomicalSunset());
  Serial.print("Astronomical Sunset: "); 
  Serial.println(sunset); 
  Serial.print("Sunset: "); 
  Serial.print(sunset/60); 
  Serial.print(":"); 
  Serial.print((sunset%60));  
}
```

Here the Output: 
```
Date: 25.9.2022
Time: 13:32:2  
__________________________________
Sunset: 1000   
Sunset: 16:40
__________________________________
Civil Sunset: 1022
Sunset: 17:2
__________________________________
Nautical Sunset: 1046
Sunset: 17:26
__________________________________
Astronomical Sunset: 1071
Sunset: 17:51
```

The sunset for this location should be around 18:54 according to various internet sites. I don't mind a few minutes off but none of the calculated sunsets come even close. 

Are the calculated values in my local time (UCT+2)? 
What does setTzOffset() do? Is it intended for DST use? 

Help is really appreciated! 
Thank you! 
Best regards, 
watzi

**Comment by buelowp** [comment]
I don't see you set the location anywhere.

```
sun.setPosition(LATITUDE, LONGITUDE, TIMEZONE);
```

has to be done somewhere for the library to know where you are trying to get values for. The reason it's close is that you're close to UTC.

**Comment by watzi3** [comment]
> I don't see you set the location anywhere.
> 
> ```
> sun.setPosition(LATITUDE, LONGITUDE, TIMEZONE);
> ```
> 
> has to be done somewhere for the library to know where you are trying to get values for. The reason it's close is that you're close to UTC.

Thank you for your time and reply. 

In the code above I forgot to paste this line (I included just the relevant lines regarding the library). In my project the location was set properly like you mentioned.  
I updated the code.

**Comment by buelowp** [comment]
In your code, you have swapped longitude and latitude. 

```
sun.setPosition(LONGITUDE,LATITUDE,TIMEZONE);
```

That's backwards, it must be LAT,LON,TZ.

**Comment by watzi3** [comment]
I feel quite stupid now! Issue solved - everything works perfect! 
Sorry for the disturbance and thank you very much for the solution and your time!
