### ISSUE TITLE
Is it ok to compile the piece of code into my company's App and published with closed source?

### ISSUE THREAD

**Issue by forunix** [buelowp/sunset#52]
Hi,
    I want to use you API of calculate sunrise and sunset in my App. However your code is licensed using GPL. Is it ok to use your code in my App without open source my App?

Thanks!

**Comment by buelowp** [comment]
No, that's the point here. If you would be willing to pay for it, then we could dual license, but otherwise, the license stands.

**Comment by buelowp** [comment]
I take that back, I cannot dual license, as the original code is not mine an is GPL. The license stands as is, and cannot be changed.
