### ISSUE TITLE
License mistake

### ISSUE THREAD

**Issue by rhn** [buelowp/sunset#7]
The README states

> This is a modification of the sunrise.c posted by Mike Chirico back in 2004.

but at the same time

> This is governed by the MIT license. Use it as you want, make changes as you want. 

Whereas Mike's [original code](http://souptonuts.sourceforge.net/code/sunrise.c.html) is under GPLv2 (check out [this archive](http://prdownloads.sourceforge.net/souptonuts/working_with_time.tar.gz?download)), which says, among other things:

>  You must cause any work that you distribute or publish, that in
>    whole or in part contains or is derived from the Program or any
>    part thereof, to be licensed as a whole at no charge to all third
>    parties under the terms of this License.

meaning that the whole Sunset library together with C++ modifications must be distributed as GPL, so putting it out as MIT is a mistake.

It would be cool if that could be corrected. Without a valid license, it's impossible to know under what terms this code can be distributed, making it effectively useless outside of personal projects.

**Comment by buelowp** [comment]
Thanks, I hadn't noticed that. I have updated to the new license and committed the changes.

**Comment by rhn** [comment]
On Tue, 23 Apr 2019 05:29:11 -0700
Peter Buelow <notifications@github.com> wrote:

> Thanks, I hadn't noticed that. I have updated to the new license and committed the changes.
> 

Awesome, thank you!

I have to note here that the original copyright notice by  has to be preserved too. It's the line in http://souptonuts.sourceforge.net/code/sunrise.c.html that says:

> Copyright (GPL) 2004   Mike Chirico mchirico@comcast.net

In general, this is the case for most free licenses, because they require attribution, and copyright (almost) never goes away on its own. In particular, GPLv2 says:

> 1. You may copy and distribute verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice [...]; keep intact all the notices that refer to this License

IANAL, but happy to help with other licensing questions from the practical side :)
